version: '2'
services:

    # See: docker/Dockerfile
    code_challenge_api:
        build: .

        restart: always

        container_name: docker_code_challenge_api

        environment:
            APACHE_RUN_USER: david
            APACHE_RUN_GROUP: david

        ports:
            - "8081:80"

        volumes:
            - "../.:/var/www/html"

        network_mode: "bridge"
